{this inc file is generated during release }
  gsIdVersionMajor = 11;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 0;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 0;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 1;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 11'*)
  (*$HPPEMIT '#define gsIdVersionMinor 0'*)
  (*$HPPEMIT '#define gsIdVersionRelease 0'*)
  (*$HPPEMIT '#define gsIdVersionBuild 1'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '11.0.0.1'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
  gsIdProductVersion = '11.0.0-alpha.1'; {do not localize}
